INSERT INTO sections (category, title, named_id) VALUES (0, 'Новини Екзархату', 'news-of-exarchate');
INSERT INTO sections (category, title, named_id) VALUES (0, 'Новини Церкви', 'news-of-church');
INSERT INTO sections (category, title, named_id) VALUES (0, 'Публікації', 'publications');
INSERT INTO sections (category, title, named_id) VALUES (1, 'Документи Церкви', 'documents-of-church');
INSERT INTO sections (category, title, named_id) VALUES (1, 'Документи Екзархату', 'documents-of-exarchate');
INSERT INTO sections (category, title, named_id) VALUES (2, 'Галерея', 'gallery');
INSERT INTO sections (category, title, named_id) VALUES (3, 'Сторінки', 'pages');
insert into types (section_id, title, named_id, item_type) values (7, 'Екзархат', 'exarchate', 'Article');
insert into articles (image_description, image_url, text, id) values ('', '', '', 1);
insert into types (section_id, title, named_id, item_type) values (7, 'Єпископи', 'bishops', 'Article');
insert into articles (image_description, image_url, text, id) values ('', '', '', 2);
insert into types (section_id, title, named_id, item_type) values (7, 'Курія', 'curia', 'Article');
insert into articles (image_description, image_url, text, id) values ('', '', '', 3);
insert into types (section_id, title, named_id, item_type) values (7, 'Комісії', 'commission', 'Article');
insert into articles (image_description, image_url, text, id) values ('', '', '', 4);
insert into types (section_id, title, named_id, item_type) values (7, 'Духовенство', 'clergy', 'Article');
insert into articles (image_description, image_url, text, id) values ('', '', '', 5);
insert into types (section_id, title, named_id, item_type) values (7, 'Пресслужба', 'press-service', 'Article');
insert into articles (image_description, image_url, text, id) values ('', '', '', 6);
insert into types (section_id, title, named_id, item_type) values (7, 'Парафії та монастирі', 'parishes-and-monasteries', 'Article');
insert into articles (image_description, image_url, text, id) values ('', '', '', 7);
insert into types (section_id, title, named_id, item_type) values (7, 'Про нас', 'about-us', 'Article');
insert into articles (image_description, image_url, text, id) values ('', '', '', 8);
insert into types (section_id, title, named_id, item_type) values (7, 'Глава і Отець УКГЦ', 'head-and-father-of-the-ugcc', 'Article');
insert into articles (image_description, image_url, text, id) values ('', '', '', 9);
insert into types (section_id, title, named_id, item_type) values (7, 'Структура церкви', 'church-structure', 'Article');
insert into articles (image_description, image_url, text, id) values ('', '', '', 10);
insert into types (section_id, title, named_id, item_type) values (7, 'Історія Донецького Екзархату', 'history-of-the-donetsk-exarchate', 'Article');
insert into articles (image_description, image_url, text, id) values ('', '', '', 11);
insert into contacts (town_and_index, address, country, phone, email) values ('', '', '', '', '');
insert into site_users (login, password, role) VALUES ('admin', '$2a$10$sj3gOaIKlitMGr.I7lm0W.pgYbhfLCIndxF89r1OTPw2jdlIOrgRW', 'ROLE_ADMIN')